# Numpy is Numerical Python.


In [1]:
import numpy as np

In [2]:
val1 = np.array([[1,2,3,4],[5,6,7,8]])
val1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
val2 = np.zeros((8,5) , dtype=int)   # Default dtype = float
val2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
val3 = np.ones((2,5) , dtype=int)
val3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
val4 = np.arange(6,40,2)
val4

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [6]:
val5 = np.linspace(10,30,5)
val5

array([10., 15., 20., 25., 30.])

In [7]:
val6 = np.random.randint(0,35,size=(4,6))
print(val6)

[[29 20  1 17 26 29]
 [33 15  5 28  7  8]
 [20 24 27 32 16 32]
 [15 33  0 17 26 24]]


In [8]:
val7 = np.full((3,4,3),6)
print(val7)

[[[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]]


In [9]:
val8 = np.identity(5)
print(val8)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
list_ = [1,2,3]
val9 = np.asarray(list_)
val9

array([1, 2, 3])

In [11]:
a = np.random.randint(1,5,(2,4))
a

array([[4, 4, 1, 4],
       [2, 2, 4, 2]])

In [12]:
k = np.random.randint(5,10,(2,4))
k

array([[9, 6, 5, 6],
       [8, 9, 8, 7]])

In [13]:
# Multiply
np.multiply(a,k)

array([[36, 24,  5, 24],
       [16, 18, 32, 14]])

In [14]:
# Divide 
np.divide(a,k)

array([[0.44444444, 0.66666667, 0.2       , 0.66666667],
       [0.25      , 0.22222222, 0.5       , 0.28571429]])

In [15]:
# multiplication
multiply = np.multiply(186, 300)
multiply

55800

# Array Operations

In [16]:
val1 = np.random.randint(1,40,(3,5))
val1

array([[21, 36, 19, 39, 19],
       [13, 22, 39, 27,  1],
       [38,  5, 12, 14,  6]])

* max

In [17]:
val2.max()


0

* min

In [18]:
val3.min()

1

 * Median

In [19]:
val4 = np.array([[1,2,3],[5,8,4]])
np.median(val4)

3.5

 # Array Manipulation

In [20]:
val1 = np.array(np.random.randint(1,5,(4,6)))
val1

array([[4, 1, 2, 4, 2, 3],
       [4, 3, 4, 2, 1, 2],
       [1, 3, 3, 2, 1, 2],
       [2, 3, 2, 2, 2, 4]])

In [21]:
transpose_array = np.transpose(val1)
transpose_array

array([[4, 4, 1, 2],
       [1, 3, 3, 3],
       [2, 4, 3, 2],
       [4, 2, 2, 2],
       [2, 1, 1, 2],
       [3, 2, 2, 4]])

In [22]:
val3.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Numpy array Attributes
* ndarray.shape

In [23]:
val1 = np.array([[1,2,3],[3,4,9]])
print(val1.shape)

(2, 3)


In [24]:
val2 = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]])
print(val2.shape)


(4, 2, 3)


In [25]:
val3 = np.array([[1,2,3],[4,5,6]])
print(f"The dimension of val3: ",val3.ndim)

The dimension of val3:  2


In [26]:
val4 = np.array([1,2,3,4,5])
print(val4.dtype)

int32


In [27]:
val5 = np.array([[1,2,3],[4,5,8]])
print(f"The total number of elements in val5 =  {val5.size}")

The total number of elements in val5 =  6


In [29]:
val6 = np.array([2,3,4])
print(val6.dtype)
print(val6)
print(val6)


int32
[2 3 4]
[2 3 4]
